
package etanah.client.carian;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CarianPersendirian_OnlinePortType", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarianPersendirianOnlinePortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfCarianInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "checkAccountByParam", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountByParam")
    @ResponseWrapper(localName = "checkAccountByParamResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountByParamResponse")
    public ArrayOfCarianInfo checkAccountByParam(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in4);

    /**
     * 
     * @return
     *     returns etanah.client.carian.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "listKodDaerah", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodDaerah")
    @ResponseWrapper(localName = "listKodDaerahResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodDaerahResponse")
    public ArrayOfUtilKod listKodDaerah();

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfDokumenCarianPersendirian
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "senaraiDokumen", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.SenaraiDokumen")
    @ResponseWrapper(localName = "senaraiDokumenResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.SenaraiDokumenResponse")
    public ArrayOfDokumenCarianPersendirian senaraiDokumen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "updateCarianAccount", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.UpdateCarianAccount")
    @ResponseWrapper(localName = "updateCarianAccountResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.UpdateCarianAccountResponse")
    public String updateCarianAccount(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        BigDecimal in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in6);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfCarianInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "checkAccountByNoLot", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountByNoLot")
    @ResponseWrapper(localName = "checkAccountByNoLotResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountByNoLotResponse")
    public ArrayOfCarianInfo checkAccountByNoLot(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        Integer in4);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return
     *     returns etanah.client.carian.ArrayOfCarianInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "checkAccountStrataByParam", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountStrataByParam")
    @ResponseWrapper(localName = "checkAccountStrataByParamResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountStrataByParamResponse")
    public ArrayOfCarianInfo checkAccountStrataByParam(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in7);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return
     *     returns etanah.client.carian.ArrayOfCarianInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "checkAccountStrataByNoLot", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountStrataByNoLot")
    @ResponseWrapper(localName = "checkAccountStrataByNoLotResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountStrataByNoLotResponse")
    public ArrayOfCarianInfo checkAccountStrataByNoLot(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        Integer in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in7);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "listKodSeksyen", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodSeksyen")
    @ResponseWrapper(localName = "listKodSeksyenResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodSeksyenResponse")
    public ArrayOfUtilKod listKodSeksyen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0);

    /**
     * 
     * @return
     *     returns etanah.client.carian.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "listKodLot", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodLot")
    @ResponseWrapper(localName = "listKodLotResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodLotResponse")
    public ArrayOfUtilKod listKodLot();

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "listKodMukim", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodMukim")
    @ResponseWrapper(localName = "listKodMukimResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodMukimResponse")
    public ArrayOfUtilKod listKodMukim(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.carian.DokumenInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "muatturundokumen", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.Muatturundokumen")
    @ResponseWrapper(localName = "muatturundokumenResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.MuatturundokumenResponse")
    public DokumenInfo muatturundokumen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        Long in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfDokumenCarianPersendirian
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "senaraiDokumenIdHakmilik", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.SenaraiDokumenIdHakmilik")
    @ResponseWrapper(localName = "senaraiDokumenIdHakmilikResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.SenaraiDokumenIdHakmilikResponse")
    public ArrayOfDokumenCarianPersendirian senaraiDokumenIdHakmilik(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1);

    /**
     * 
     * @return
     *     returns etanah.client.carian.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "listKodHakmilik", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodHakmilik")
    @ResponseWrapper(localName = "listKodHakmilikResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.ListKodHakmilikResponse")
    public ArrayOfUtilKod listKodHakmilik();

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.carian.ArrayOfCarianInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
    @RequestWrapper(localName = "checkAccount", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccount")
    @ResponseWrapper(localName = "checkAccountResponse", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", className = "etanah.client.carian.CheckAccountResponse")
    public ArrayOfCarianInfo checkAccount(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS")
        String in1);

}
