
package etanah.client.bayar;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Bayaran_OnlinePortType", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BayaranOnlinePortType {


    /**
     * 
     * @param in0
     */
    @WebMethod
    @RequestWrapper(localName = "daftarPenggunaBaru", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.DaftarPenggunaBaru")
    @ResponseWrapper(localName = "daftarPenggunaBaruResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.DaftarPenggunaBaruResponse")
    public void daftarPenggunaBaru(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        FormDaftarPengguna in0);

    /**
     * 
     * @return
     *     returns etanah.client.bayar.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "listKodDaerah", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ListKodDaerah")
    @ResponseWrapper(localName = "listKodDaerahResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ListKodDaerahResponse")
    public ArrayOfUtilKod listKodDaerah();

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.bayar.ArrayOfDokumenCarianPersendirian
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "senaraiDokumen", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.SenaraiDokumen")
    @ResponseWrapper(localName = "senaraiDokumenResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.SenaraiDokumenResponse")
    public ArrayOfDokumenCarianPersendirian senaraiDokumen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.bayar.ArrayOfSejarahTransaksiPortal
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "sejarahTransaksi", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.SejarahTransaksi")
    @ResponseWrapper(localName = "sejarahTransaksiResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.SejarahTransaksiResponse")
    public ArrayOfSejarahTransaksiPortal sejarahTransaksi(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in2);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "updateCarianAccount", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateCarianAccount")
    @ResponseWrapper(localName = "updateCarianAccountResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateCarianAccountResponse")
    public String updateCarianAccount(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        BigDecimal in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in7);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "updateTransaction", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateTransaction")
    @ResponseWrapper(localName = "updateTransactionResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateTransactionResponse")
    public String updateTransaction(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        BigDecimal in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in3);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "updateUserAccount", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateUserAccount")
    @ResponseWrapper(localName = "updateUserAccountResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateUserAccountResponse")
    public String updateUserAccount(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        BigDecimal in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in7);

    /**
     * 
     * @param in0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "lupaKataLaluan", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.LupaKataLaluan")
    @ResponseWrapper(localName = "lupaKataLaluanResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.LupaKataLaluanResponse")
    public boolean lupaKataLaluan(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.bayar.Konfigurasi
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "config", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.Config")
    @ResponseWrapper(localName = "configResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ConfigResponse")
    public Konfigurasi config(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.bayar.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "listKodMukim", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ListKodMukim")
    @ResponseWrapper(localName = "listKodMukimResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ListKodMukimResponse")
    public ArrayOfUtilKod listKodMukim(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.bayar.StatusLogin
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "logMasuk", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.LogMasuk")
    @ResponseWrapper(localName = "logMasukResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.LogMasukResponse")
    public StatusLogin logMasuk(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in1);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.bayar.FormDaftarPengguna
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "profilPengguna", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ProfilPengguna")
    @ResponseWrapper(localName = "profilPenggunaResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ProfilPenggunaResponse")
    public FormDaftarPengguna profilPengguna(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.client.bayar.DokumenInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "muatturundokumen", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.Muatturundokumen")
    @ResponseWrapper(localName = "muatturundokumenResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.MuatturundokumenResponse")
    public DokumenInfo muatturundokumen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        Long in0);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @param in7
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "updateAccountPukal", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateAccountPukal")
    @ResponseWrapper(localName = "updateAccountPukalResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.UpdateAccountPukalResponse")
    public String updateAccountPukal(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        ArrayOfAkaunForm in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        BigDecimal in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in7);

    /**
     * 
     * @return
     *     returns etanah.client.bayar.ArrayOfUtilKod
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "listKodHakmilik", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ListKodHakmilik")
    @ResponseWrapper(localName = "listKodHakmilikResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.ListKodHakmilikResponse")
    public ArrayOfUtilKod listKodHakmilik();

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns etanah.client.bayar.ArrayOfAccountInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
    @RequestWrapper(localName = "checkAccount", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.CheckAccount")
    @ResponseWrapper(localName = "checkAccountResponse", targetNamespace = "http://localhost:8080/bayaranOnlineWS", className = "etanah.client.bayar.CheckAccountResponse")
    public ArrayOfAccountInfo checkAccount(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/bayaranOnlineWS")
        String in1);

}
