
package etanah.client.bayar;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Bayaran_Online", targetNamespace = "http://localhost:8080/bayaranOnlineWS", wsdlLocation = "file:/C:/Users/mohd.faidzal/AppData/Local/Temp/tempdir7960686524451714891.tmp/Bayaran_Online_1.wsdl")
public class BayaranOnline
    extends Service
{

    private final static URL BAYARANONLINE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(etanah.client.bayar.BayaranOnline.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = etanah.client.bayar.BayaranOnline.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/mohd.faidzal/AppData/Local/Temp/tempdir7960686524451714891.tmp/Bayaran_Online_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/mohd.faidzal/AppData/Local/Temp/tempdir7960686524451714891.tmp/Bayaran_Online_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BAYARANONLINE_WSDL_LOCATION = url;
    }

    public BayaranOnline(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BayaranOnline() {
        super(BAYARANONLINE_WSDL_LOCATION, new QName("http://localhost:8080/bayaranOnlineWS", "Bayaran_Online"));
    }

    /**
     * 
     * @return
     *     returns BayaranOnlinePortType
     */
    @WebEndpoint(name = "Bayaran_OnlineHttpPort")
    public BayaranOnlinePortType getBayaranOnlineHttpPort() {
        return super.getPort(new QName("http://localhost:8080/bayaranOnlineWS", "Bayaran_OnlineHttpPort"), BayaranOnlinePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BayaranOnlinePortType
     */
    @WebEndpoint(name = "Bayaran_OnlineHttpPort")
    public BayaranOnlinePortType getBayaranOnlineHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/bayaranOnlineWS", "Bayaran_OnlineHttpPort"), BayaranOnlinePortType.class, features);
    }

}
