
package etanah.client.etapp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtappPermohonanPortType", targetNamespace = "http://localhost:8080/EtappPermohonan")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtappPermohonanPortType {


    /**
     * 
     * @param in6
     * @param in5
     * @param in8
     * @param in7
     * @param in9
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns etanah.client.etapp.MaklumatPermohonan
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "generatePermohonan", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.GeneratePermohonan")
    @ResponseWrapper(localName = "generatePermohonanResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.GeneratePermohonanResponse")
    public MaklumatPermohonan generatePermohonan(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in9);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "sijilPembebasanUkurMyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.SijilPembebasanUkurMyEtaPP")
    @ResponseWrapper(localName = "sijilPembebasanUkurMyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.SijilPembebasanUkurMyEtaPPResponse")
    public String sijilPembebasanUkurMyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "daftarPermohonanMyEtaPPBorangAMMk", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.DaftarPermohonanMyEtaPPBorangAMMk")
    @ResponseWrapper(localName = "daftarPermohonanMyEtaPPBorangAMMkResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.DaftarPermohonanMyEtaPPBorangAMMkResponse")
    public String daftarPermohonanMyEtaPPBorangAMMk(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        MaklumatPermohonanSek4MyEtaPP in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfHakmilikPermohonanMyEtaPP in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        LampiranMyEtaPP in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "maklumanPenghantaranPUMyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.MaklumanPenghantaranPUMyEtaPP")
    @ResponseWrapper(localName = "maklumanPenghantaranPUMyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.MaklumanPenghantaranPUMyEtaPPResponse")
    public String maklumanPenghantaranPUMyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "endorsBorangDMaklumatWartaMyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.EndorsBorangDMaklumatWartaMyEtaPP")
    @ResponseWrapper(localName = "endorsBorangDMaklumatWartaMyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.EndorsBorangDMaklumatWartaMyEtaPPResponse")
    public String endorsBorangDMaklumatWartaMyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "borangCdanMMKMyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.BorangCdanMMKMyEtaPP")
    @ResponseWrapper(localName = "borangCdanMMKMyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.BorangCdanMMKMyEtaPPResponse")
    public String borangCdanMMKMyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        LampiranMyEtaPP in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in2);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "daftarPermohonanSek8MyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.DaftarPermohonanSek8MyEtaPP")
    @ResponseWrapper(localName = "daftarPermohonanSek8MyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.DaftarPermohonanSek8MyEtaPPResponse")
    public String daftarPermohonanSek8MyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        MaklumatPermohonanSek8MyEtaPP in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfHakmilikPermohonanMyEtaPP in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        LampiranMyEtaPP in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns etanah.client.etapp.MaklumatHakmilikMyEtaPP
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "maklumatHakmilik", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.MaklumatHakmilik")
    @ResponseWrapper(localName = "maklumatHakmilikResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.MaklumatHakmilikResponse")
    public MaklumatHakmilikMyEtaPP maklumatHakmilik(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "endorsBorangKMyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.EndorsBorangKMyEtaPP")
    @ResponseWrapper(localName = "endorsBorangKMyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.EndorsBorangKMyEtaPPResponse")
    public String endorsBorangKMyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/EtappPermohonan")
    @RequestWrapper(localName = "maklumatWartaBorangBMyEtaPP", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.MaklumatWartaBorangBMyEtaPP")
    @ResponseWrapper(localName = "maklumatWartaBorangBMyEtaPPResponse", targetNamespace = "http://localhost:8080/EtappPermohonan", className = "etanah.client.etapp.MaklumatWartaBorangBMyEtaPPResponse")
    public String maklumatWartaBorangBMyEtaPP(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/EtappPermohonan")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/EtappPermohonan")
        ArrayOfLampiranMyEtaPP in3);

}
