
package etanah.integration.ispeks;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DecryptServiceImplService", targetNamespace = "http://pgpfile.gpg.etanah/", wsdlLocation = "http://kjsb.zapto.org:9999/ws/ispeks?wsdl")
public class DecryptServiceImplService
    extends Service
{

    private final static URL DECRYPTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(etanah.integration.ispeks.DecryptServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = etanah.integration.ispeks.DecryptServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://kjsb.zapto.org:9999/ws/ispeks?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://kjsb.zapto.org:9999/ws/ispeks?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DECRYPTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DecryptServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DecryptServiceImplService() {
        super(DECRYPTSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://pgpfile.gpg.etanah/", "DecryptServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DecryptService
     */
    @WebEndpoint(name = "DecryptServiceImplPort")
    public DecryptService getDecryptServiceImplPort() {
        return super.getPort(new QName("http://pgpfile.gpg.etanah/", "DecryptServiceImplPort"), DecryptService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DecryptService
     */
    @WebEndpoint(name = "DecryptServiceImplPort")
    public DecryptService getDecryptServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pgpfile.gpg.etanah/", "DecryptServiceImplPort"), DecryptService.class, features);
    }

}
