
package etanah.client.carianenq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarianEnquiry", targetNamespace = "http://localhost:8080/CarianEnquiry", wsdlLocation = "http://192.168.0.10:7009/etanah/services/CarianEnquiry?wsdl")
public class CarianEnquiry
    extends Service
{

    private final static URL CARIANENQUIRY_WSDL_LOCATION;
    private final static WebServiceException CARIANENQUIRY_EXCEPTION;
    private final static QName CARIANENQUIRY_QNAME = new QName("http://localhost:8080/CarianEnquiry", "CarianEnquiry");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.10:7009/etanah/services/CarianEnquiry?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARIANENQUIRY_WSDL_LOCATION = url;
        CARIANENQUIRY_EXCEPTION = e;
    }

    public CarianEnquiry() {
        super(__getWsdlLocation(), CARIANENQUIRY_QNAME);
    }

    public CarianEnquiry(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARIANENQUIRY_QNAME, features);
    }

    public CarianEnquiry(URL wsdlLocation) {
        super(wsdlLocation, CARIANENQUIRY_QNAME);
    }

    public CarianEnquiry(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARIANENQUIRY_QNAME, features);
    }

    public CarianEnquiry(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarianEnquiry(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarianEnquiryPortType
     */
    @WebEndpoint(name = "CarianEnquiryHttpPort")
    public CarianEnquiryPortType getCarianEnquiryHttpPort() {
        return super.getPort(new QName("http://localhost:8080/CarianEnquiry", "CarianEnquiryHttpPort"), CarianEnquiryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarianEnquiryPortType
     */
    @WebEndpoint(name = "CarianEnquiryHttpPort")
    public CarianEnquiryPortType getCarianEnquiryHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/CarianEnquiry", "CarianEnquiryHttpPort"), CarianEnquiryPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARIANENQUIRY_EXCEPTION!= null) {
            throw CARIANENQUIRY_EXCEPTION;
        }
        return CARIANENQUIRY_WSDL_LOCATION;
    }

}
