
package etanah.client.carianenq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarianEnquiryPortType", targetNamespace = "http://localhost:8080/CarianEnquiry")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarianEnquiryPortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns etanah.client.carianenq.ArrayOfAnyType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/CarianEnquiry")
    @RequestWrapper(localName = "getSijil", targetNamespace = "http://localhost:8080/CarianEnquiry", className = "etanah.client.carianenq.GetSijil")
    @ResponseWrapper(localName = "getSijilResponse", targetNamespace = "http://localhost:8080/CarianEnquiry", className = "etanah.client.carianenq.GetSijilResponse")
    public ArrayOfAnyType getSijil(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/CarianEnquiry")
        ArrayOfString in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in3);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns etanah.client.carianenq.ArrayOfAnyType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/CarianEnquiry")
    @RequestWrapper(localName = "getSijil1", targetNamespace = "http://localhost:8080/CarianEnquiry", className = "etanah.client.carianenq.GetSijil1")
    @ResponseWrapper(localName = "getSijil1Response", targetNamespace = "http://localhost:8080/CarianEnquiry", className = "etanah.client.carianenq.GetSijil1Response")
    public ArrayOfAnyType getSijil1(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/CarianEnquiry")
        ArrayOfString in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:8080/CarianEnquiry")
        String in4);

}
