
package etanah.client.cukai.strata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CukaiPetakOnline", targetNamespace = "http://localhost:8080/cukaipetakonlineWS", wsdlLocation = "http://192.168.0.10:7009/etanah/services/CukaiPetakOnline?wsdl")
public class CukaiPetakOnline
    extends Service
{

    private final static URL CUKAIPETAKONLINE_WSDL_LOCATION;
    private final static WebServiceException CUKAIPETAKONLINE_EXCEPTION;
    private final static QName CUKAIPETAKONLINE_QNAME = new QName("http://localhost:8080/cukaipetakonlineWS", "CukaiPetakOnline");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.10:7009/etanah/services/CukaiPetakOnline?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUKAIPETAKONLINE_WSDL_LOCATION = url;
        CUKAIPETAKONLINE_EXCEPTION = e;
    }

    public CukaiPetakOnline() {
        super(__getWsdlLocation(), CUKAIPETAKONLINE_QNAME);
    }

    public CukaiPetakOnline(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUKAIPETAKONLINE_QNAME, features);
    }

    public CukaiPetakOnline(URL wsdlLocation) {
        super(wsdlLocation, CUKAIPETAKONLINE_QNAME);
    }

    public CukaiPetakOnline(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUKAIPETAKONLINE_QNAME, features);
    }

    public CukaiPetakOnline(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CukaiPetakOnline(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CukaiPetakOnlinePortType
     */
    @WebEndpoint(name = "CukaiPetakOnlineHttpPort")
    public CukaiPetakOnlinePortType getCukaiPetakOnlineHttpPort() {
        return super.getPort(new QName("http://localhost:8080/cukaipetakonlineWS", "CukaiPetakOnlineHttpPort"), CukaiPetakOnlinePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CukaiPetakOnlinePortType
     */
    @WebEndpoint(name = "CukaiPetakOnlineHttpPort")
    public CukaiPetakOnlinePortType getCukaiPetakOnlineHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/cukaipetakonlineWS", "CukaiPetakOnlineHttpPort"), CukaiPetakOnlinePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUKAIPETAKONLINE_EXCEPTION!= null) {
            throw CUKAIPETAKONLINE_EXCEPTION;
        }
        return CUKAIPETAKONLINE_WSDL_LOCATION;
    }

}
