
package etanah.client.wslog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsLogPortType", targetNamespace = "http://localhost:8080/logWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsLogPortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/logWS")
    @RequestWrapper(localName = "insertLog", targetNamespace = "http://localhost:8080/logWS", className = "etanah.client.wslog.InsertLog")
    @ResponseWrapper(localName = "insertLogResponse", targetNamespace = "http://localhost:8080/logWS", className = "etanah.client.wslog.InsertLogResponse")
    public Long insertLog(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/logWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/logWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/logWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/logWS")
        String in3);

    /**
     * 
     * @param in1
     * @param in0
     */
    @WebMethod
    @RequestWrapper(localName = "updateLog", targetNamespace = "http://localhost:8080/logWS", className = "etanah.client.wslog.UpdateLog")
    @ResponseWrapper(localName = "updateLogResponse", targetNamespace = "http://localhost:8080/logWS", className = "etanah.client.wslog.UpdateLogResponse")
    public void updateLog(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/logWS")
        Long in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/logWS")
        String in1);

}
