
package localhost._8080.perkhidmatanonlinews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PerkhidmatanAtasTalian", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", wsdlLocation = "http://192.168.0.10:7009/etanah/services/PerkhidmatanAtasTalian?wsdl")
public class PerkhidmatanAtasTalian
    extends Service
{

    private final static URL PERKHIDMATANATASTALIAN_WSDL_LOCATION;
    private final static WebServiceException PERKHIDMATANATASTALIAN_EXCEPTION;
    private final static QName PERKHIDMATANATASTALIAN_QNAME = new QName("http://localhost:8080/perkhidmatanOnlineWS", "PerkhidmatanAtasTalian");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.10:7009/etanah/services/PerkhidmatanAtasTalian?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERKHIDMATANATASTALIAN_WSDL_LOCATION = url;
        PERKHIDMATANATASTALIAN_EXCEPTION = e;
    }

    public PerkhidmatanAtasTalian() {
        super(__getWsdlLocation(), PERKHIDMATANATASTALIAN_QNAME);
    }

    public PerkhidmatanAtasTalian(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERKHIDMATANATASTALIAN_QNAME, features);
    }

    public PerkhidmatanAtasTalian(URL wsdlLocation) {
        super(wsdlLocation, PERKHIDMATANATASTALIAN_QNAME);
    }

    public PerkhidmatanAtasTalian(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERKHIDMATANATASTALIAN_QNAME, features);
    }

    public PerkhidmatanAtasTalian(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PerkhidmatanAtasTalian(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PerkhidmatanAtasTalianPortType
     */
    @WebEndpoint(name = "PerkhidmatanAtasTalianHttpPort")
    public PerkhidmatanAtasTalianPortType getPerkhidmatanAtasTalianHttpPort() {
        return super.getPort(new QName("http://localhost:8080/perkhidmatanOnlineWS", "PerkhidmatanAtasTalianHttpPort"), PerkhidmatanAtasTalianPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PerkhidmatanAtasTalianPortType
     */
    @WebEndpoint(name = "PerkhidmatanAtasTalianHttpPort")
    public PerkhidmatanAtasTalianPortType getPerkhidmatanAtasTalianHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/perkhidmatanOnlineWS", "PerkhidmatanAtasTalianHttpPort"), PerkhidmatanAtasTalianPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERKHIDMATANATASTALIAN_EXCEPTION!= null) {
            throw PERKHIDMATANATASTALIAN_EXCEPTION;
        }
        return PERKHIDMATANATASTALIAN_WSDL_LOCATION;
    }

}
