
package etanah.ws.ispeks.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WsIspeks", targetNamespace = "http://localhost:8080/ispeksWS", wsdlLocation = "http://10.66.130.10:7003/etanah/services/WsIspeks?wsdl")
public class WsIspeks
    extends Service
{

    private final static URL WSISPEKS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(etanah.ws.ispeks.client.WsIspeks.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = etanah.ws.ispeks.client.WsIspeks.class.getResource(".");
            url = new URL(baseUrl, "http://10.66.130.10:7003/etanah/services/WsIspeks?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.66.130.10:7003/etanah/services/WsIspeks?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSISPEKS_WSDL_LOCATION = url;
    }

    public WsIspeks(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsIspeks() {
        super(WSISPEKS_WSDL_LOCATION, new QName("http://localhost:8080/ispeksWS", "WsIspeks"));
    }

    /**
     * 
     * @return
     *     returns WsIspeksPortType
     */
    @WebEndpoint(name = "WsIspeksHttpPort")
    public WsIspeksPortType getWsIspeksHttpPort() {
        return super.getPort(new QName("http://localhost:8080/ispeksWS", "WsIspeksHttpPort"), WsIspeksPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsIspeksPortType
     */
    @WebEndpoint(name = "WsIspeksHttpPort")
    public WsIspeksPortType getWsIspeksHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/ispeksWS", "WsIspeksHttpPort"), WsIspeksPortType.class, features);
    }

}
