<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    
     targetNamespace="http://localhost:8080/cukaipetakonlineWS"
     xmlns:ns1="http://form.ws.portal.view.etanah"
     xmlns:soapenc12="http://www.w3.org/2003/05/soap-encoding"
     xmlns:tns="http://localhost:8080/cukaipetakonlineWS"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap11="http://schemas.xmlsoap.org/soap/envelope/"
     xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:soapenc11="http://schemas.xmlsoap.org/soap/encoding/"
     xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"
    >
    <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://localhost:8080/cukaipetakonlineWS">
<xsd:element name="semakCukaiStrataIdHakmilik">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="in0" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="semakCukaiStrataIdHakmilikResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="out" nillable="true" type="ns1:ArrayOfCukaiStrataForm"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="semakCukaiStrataByNoLot">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="in0" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in1" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in2" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in3" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in4" nillable="true" type="xsd:int"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in5" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in6" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in7" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="semakCukaiStrataByNoLotResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="out" nillable="true" type="ns1:ArrayOfCukaiStrataForm"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="terimaBayaran">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="in0" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in1" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in2" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in3" nillable="true" type="xsd:decimal"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in4" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in5" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in6" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="terimaBayaranResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="out" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="semakCukaiStrataByParam">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="in0" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in1" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in2" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in3" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in4" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in5" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in6" nillable="true" type="xsd:string"/>
<xsd:element maxOccurs="1" minOccurs="1" name="in7" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
<xsd:element name="semakCukaiStrataByParamResponse">
<xsd:complexType>
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="1" name="out" nillable="true" type="ns1:ArrayOfCukaiStrataForm"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://form.ws.portal.view.etanah">
<xsd:complexType name="ArrayOfCukaiStrataForm">
<xsd:sequence>
<xsd:element maxOccurs="unbounded" minOccurs="0" name="CukaiStrataForm" nillable="true" type="ns1:CukaiStrataForm"/>
</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="CukaiStrataForm">
<xsd:sequence>
<xsd:element minOccurs="0" name="akaunBatal" type="xsd:boolean"/>
<xsd:element minOccurs="0" name="alamat" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="bandarpekanmukim" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="borang11" nillable="true" type="xsd:decimal"/>
<xsd:element minOccurs="0" name="cukaiSemasa" nillable="true" type="xsd:decimal"/>
<xsd:element minOccurs="0" name="daerah" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="dendaLewatSemasa" nillable="true" type="xsd:decimal"/>
<xsd:element minOccurs="0" name="idHakmilik" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="jenisHakmilik" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="jumlahBayaran" nillable="true" type="xsd:decimal"/>
<xsd:element minOccurs="0" name="jumlahKeseluruhan" nillable="true" type="xsd:decimal"/>
<xsd:element minOccurs="0" name="kodCaw" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodCawValue" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodCukaiPetak" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodDaerah" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodDendaLewat" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodLot" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodTunggakanCukaiPetak" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodTunggakanDendaLewat" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kodborang11" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="listSejarahCukai" nillable="true" type="ns1:ArrayOfSejarahCukai"/>
<xsd:element minOccurs="0" name="luasAksesori" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="luasPetak" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="namaPemilik" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noBangunan" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noHakmilik" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noLotPt" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noPetak" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noResit" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noTingkat" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="seksyen" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="statusAkaun" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="statusBayaran" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="tarikhBayaran" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="tunggakanCukai" nillable="true" type="xsd:decimal"/>
<xsd:element minOccurs="0" name="tunggakanDendaLewat" nillable="true" type="xsd:decimal"/>
</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="ArrayOfSejarahCukai">
<xsd:sequence>
<xsd:element maxOccurs="unbounded" minOccurs="0" name="SejarahCukai" nillable="true" type="ns1:SejarahCukai"/>
</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="SejarahCukai">
<xsd:sequence>
<xsd:element minOccurs="0" name="amaun" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="kaedahBayaran" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="noResit" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="pusatKutipan" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="tahun" nillable="true" type="xsd:string"/>
<xsd:element minOccurs="0" name="tarikh" type="xsd:dateTime"/>
</xsd:sequence>
</xsd:complexType>
</xsd:schema>
    </wsdl:types>
    <wsdl:message name="semakCukaiStrataIdHakmilikRequest">
        <wsdl:part name="parameters" element="tns:semakCukaiStrataIdHakmilik"/>
    </wsdl:message>
    <wsdl:message name="semakCukaiStrataIdHakmilikResponse">
        <wsdl:part name="parameters" element="tns:semakCukaiStrataIdHakmilikResponse"/>
    </wsdl:message>
    <wsdl:message name="semakCukaiStrataByNoLotRequest">
        <wsdl:part name="parameters" element="tns:semakCukaiStrataByNoLot"/>
    </wsdl:message>
    <wsdl:message name="semakCukaiStrataByNoLotResponse">
        <wsdl:part name="parameters" element="tns:semakCukaiStrataByNoLotResponse"/>
    </wsdl:message>
    <wsdl:message name="terimaBayaranRequest">
        <wsdl:part name="parameters" element="tns:terimaBayaran"/>
    </wsdl:message>
    <wsdl:message name="terimaBayaranResponse">
        <wsdl:part name="parameters" element="tns:terimaBayaranResponse"/>
    </wsdl:message>
    <wsdl:message name="semakCukaiStrataByParamRequest">
        <wsdl:part name="parameters" element="tns:semakCukaiStrataByParam"/>
    </wsdl:message>
    <wsdl:message name="semakCukaiStrataByParamResponse">
        <wsdl:part name="parameters" element="tns:semakCukaiStrataByParamResponse"/>
    </wsdl:message>
    <wsdl:portType name="CukaiPetakOnlinePortType">
        <wsdl:operation name="semakCukaiStrataIdHakmilik">
            <wsdl:input name="semakCukaiStrataIdHakmilikRequest" message="tns:semakCukaiStrataIdHakmilikRequest"/>
            <wsdl:output name="semakCukaiStrataIdHakmilikResponse" message="tns:semakCukaiStrataIdHakmilikResponse"/>
        </wsdl:operation>
        <wsdl:operation name="semakCukaiStrataByNoLot">
            <wsdl:input name="semakCukaiStrataByNoLotRequest" message="tns:semakCukaiStrataByNoLotRequest"/>
            <wsdl:output name="semakCukaiStrataByNoLotResponse" message="tns:semakCukaiStrataByNoLotResponse"/>
        </wsdl:operation>
        <wsdl:operation name="terimaBayaran">
            <wsdl:input name="terimaBayaranRequest" message="tns:terimaBayaranRequest"/>
            <wsdl:output name="terimaBayaranResponse" message="tns:terimaBayaranResponse"/>
        </wsdl:operation>
        <wsdl:operation name="semakCukaiStrataByParam">
            <wsdl:input name="semakCukaiStrataByParamRequest" message="tns:semakCukaiStrataByParamRequest"/>
            <wsdl:output name="semakCukaiStrataByParamResponse" message="tns:semakCukaiStrataByParamResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CukaiPetakOnlineHttpBinding" type="tns:CukaiPetakOnlinePortType">
        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="semakCukaiStrataIdHakmilik">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="semakCukaiStrataIdHakmilikRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="semakCukaiStrataIdHakmilikResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="semakCukaiStrataByNoLot">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="semakCukaiStrataByNoLotRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="semakCukaiStrataByNoLotResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="terimaBayaran">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="terimaBayaranRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="terimaBayaranResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="semakCukaiStrataByParam">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="semakCukaiStrataByParamRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="semakCukaiStrataByParamResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CukaiPetakOnline">
        <wsdl:port name="CukaiPetakOnlineHttpPort" binding="tns:CukaiPetakOnlineHttpBinding">
            <wsdlsoap:address location="http://192.168.0.10:7009/etanah/services/CukaiPetakOnline"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
