
package localhost._8080.perkhidmatanonlinews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import etanah.view.dokumen.ws.DokumenInfo;
import etanah.view.portal.service.ws.ArrayOfPengumumanForm;
import etanah.view.portal.service.ws.ArrayOfSenaraiBandarPekanMukim;
import etanah.view.portal.service.ws.ArrayOfSenaraiDokumen;
import etanah.view.portal.service.ws.ArrayOfSenaraiKodDaerah;
import etanah.view.portal.service.ws.ArrayOfSenaraiKodHakmilik;
import etanah.view.portal.service.ws.ArrayOfSenaraiKodSeksyen;
import etanah.view.portal.service.ws.ArrayOfSenaraiUrusan;
import etanah.view.portal.service.ws.ArrayOfStatusPermohonan;
import etanah.view.portal.service.ws.ArrayOfStatusSemakanAkaun;
import etanah.view.portal.service.ws.StatusPermohonan;
import etanah.view.portal.service.ws.StatusSemakanAkaun;
import etanah.view.portal.service.ws.StatusTukarGanti;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PerkhidmatanAtasTalianPortType", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
@XmlSeeAlso({
    etanah.view.dokumen.ws.ObjectFactory.class,
    etanah.view.portal.service.ws.ObjectFactory.class,
    localhost._8080.perkhidmatanonlinews.ObjectFactory.class
})
public interface PerkhidmatanAtasTalianPortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.StatusTukarGanti
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "statusTukarGantiByPartial", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.StatusTukarGantiByPartial")
    @ResponseWrapper(localName = "statusTukarGantiByPartialResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.StatusTukarGantiByPartialResponse")
    public StatusTukarGanti statusTukarGantiByPartial(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in3);

    /**
     * 
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfSenaraiKodDaerah
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "listKodDaerah", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListKodDaerah")
    @ResponseWrapper(localName = "listKodDaerahResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListKodDaerahResponse")
    public ArrayOfSenaraiKodDaerah listKodDaerah();

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.dokumen.ws.DokumenInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "muatTurunBilCukai", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.MuatTurunBilCukai")
    @ResponseWrapper(localName = "muatTurunBilCukaiResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.MuatTurunBilCukaiResponse")
    public DokumenInfo muatTurunBilCukai(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfPengumumanForm
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "listPengumuman", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListPengumuman")
    @ResponseWrapper(localName = "listPengumumanResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListPengumumanResponse")
    public ArrayOfPengumumanForm listPengumuman();

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfStatusSemakanAkaun
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findStatusSemakanAkaunByNoPengenalan", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusSemakanAkaunByNoPengenalan")
    @ResponseWrapper(localName = "findStatusSemakanAkaunByNoPengenalanResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusSemakanAkaunByNoPengenalanResponse")
    public ArrayOfStatusSemakanAkaun findStatusSemakanAkaunByNoPengenalan(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfSenaraiBandarPekanMukim
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "listBandarPekanMukim", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListBandarPekanMukim")
    @ResponseWrapper(localName = "listBandarPekanMukimResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListBandarPekanMukimResponse")
    public ArrayOfSenaraiBandarPekanMukim listBandarPekanMukim(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.dokumen.ws.DokumenInfo
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "muatTurunDokumen", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.MuatTurunDokumen")
    @ResponseWrapper(localName = "muatTurunDokumenResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.MuatTurunDokumenResponse")
    public DokumenInfo muatTurunDokumen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfStatusPermohonan
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findStatusPermohonanByNoPengenalan", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusPermohonanByNoPengenalan")
    @ResponseWrapper(localName = "findStatusPermohonanByNoPengenalanResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusPermohonanByNoPengenalanResponse")
    public ArrayOfStatusPermohonan findStatusPermohonanByNoPengenalan(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfSenaraiKodSeksyen
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "listKodSeksyen", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListKodSeksyen")
    @ResponseWrapper(localName = "listKodSeksyenResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListKodSeksyenResponse")
    public ArrayOfSenaraiKodSeksyen listKodSeksyen(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.StatusSemakanAkaun
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findStatusSemakanAkaun", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusSemakanAkaun")
    @ResponseWrapper(localName = "findStatusSemakanAkaunResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusSemakanAkaunResponse")
    public StatusSemakanAkaun findStatusSemakanAkaun(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfSenaraiDokumen
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findbyKodUrusan", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindbyKodUrusan")
    @ResponseWrapper(localName = "findbyKodUrusanResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindbyKodUrusanResponse")
    public ArrayOfSenaraiDokumen findbyKodUrusan(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfSenaraiKodHakmilik
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "listKod", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListKod")
    @ResponseWrapper(localName = "listKodResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.ListKodResponse")
    public ArrayOfSenaraiKodHakmilik listKod();

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.ArrayOfSenaraiUrusan
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findByKataKunci", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindByKataKunci")
    @ResponseWrapper(localName = "findByKataKunciResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindByKataKunciResponse")
    public ArrayOfSenaraiUrusan findByKataKunci(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.StatusTukarGanti
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findStatusTukarGanti", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusTukarGanti")
    @ResponseWrapper(localName = "findStatusTukarGantiResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusTukarGantiResponse")
    public StatusTukarGanti findStatusTukarGanti(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns etanah.view.portal.service.ws.StatusPermohonan
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
    @RequestWrapper(localName = "findStatusPermohonan", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusPermohonan")
    @ResponseWrapper(localName = "findStatusPermohonanResponse", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS", className = "localhost._8080.perkhidmatanonlinews.FindStatusPermohonanResponse")
    public StatusPermohonan findStatusPermohonan(
        @WebParam(name = "in0", targetNamespace = "http://localhost:8080/perkhidmatanOnlineWS")
        String in0);

}
