
package etanah.client.etapp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EtappPermohonan", targetNamespace = "http://localhost:8080/EtappPermohonan", wsdlLocation = "http://192.168.0.10:7009/etanah/services/EtappPermohonan?wsdl")
public class EtappPermohonan
    extends Service
{

    private final static URL ETAPPPERMOHONAN_WSDL_LOCATION;
    private final static WebServiceException ETAPPPERMOHONAN_EXCEPTION;
    private final static QName ETAPPPERMOHONAN_QNAME = new QName("http://localhost:8080/EtappPermohonan", "EtappPermohonan");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.0.10:7009/etanah/services/EtappPermohonan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ETAPPPERMOHONAN_WSDL_LOCATION = url;
        ETAPPPERMOHONAN_EXCEPTION = e;
    }

    public EtappPermohonan() {
        super(__getWsdlLocation(), ETAPPPERMOHONAN_QNAME);
    }

    public EtappPermohonan(WebServiceFeature... features) {
        super(__getWsdlLocation(), ETAPPPERMOHONAN_QNAME, features);
    }

    public EtappPermohonan(URL wsdlLocation) {
        super(wsdlLocation, ETAPPPERMOHONAN_QNAME);
    }

    public EtappPermohonan(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ETAPPPERMOHONAN_QNAME, features);
    }

    public EtappPermohonan(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EtappPermohonan(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EtappPermohonanPortType
     */
    @WebEndpoint(name = "EtappPermohonanHttpPort")
    public EtappPermohonanPortType getEtappPermohonanHttpPort() {
        return super.getPort(new QName("http://localhost:8080/EtappPermohonan", "EtappPermohonanHttpPort"), EtappPermohonanPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EtappPermohonanPortType
     */
    @WebEndpoint(name = "EtappPermohonanHttpPort")
    public EtappPermohonanPortType getEtappPermohonanHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/EtappPermohonan", "EtappPermohonanHttpPort"), EtappPermohonanPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ETAPPPERMOHONAN_EXCEPTION!= null) {
            throw ETAPPPERMOHONAN_EXCEPTION;
        }
        return ETAPPPERMOHONAN_WSDL_LOCATION;
    }

}
