
package etanah.client.carian;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CarianPersendirian_Online", targetNamespace = "http://localhost:8080/carianPersendirianOnlineWS", wsdlLocation = "http://localhost:8093/etanahViewController/services/CarianPersendirian_Online?wsdl")
public class CarianPersendirianOnline
    extends Service
{

    private final static URL CARIANPERSENDIRIANONLINE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(etanah.client.carian.CarianPersendirianOnline.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = etanah.client.carian.CarianPersendirianOnline.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8093/etanahViewController/services/CarianPersendirian_Online?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8093/etanahViewController/services/CarianPersendirian_Online?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CARIANPERSENDIRIANONLINE_WSDL_LOCATION = url;
    }

    public CarianPersendirianOnline(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarianPersendirianOnline() {
        super(CARIANPERSENDIRIANONLINE_WSDL_LOCATION, new QName("http://localhost:8080/carianPersendirianOnlineWS", "CarianPersendirian_Online"));
    }

    /**
     * 
     * @return
     *     returns CarianPersendirianOnlinePortType
     */
    @WebEndpoint(name = "CarianPersendirian_OnlineHttpPort")
    public CarianPersendirianOnlinePortType getCarianPersendirianOnlineHttpPort() {
        return super.getPort(new QName("http://localhost:8080/carianPersendirianOnlineWS", "CarianPersendirian_OnlineHttpPort"), CarianPersendirianOnlinePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarianPersendirianOnlinePortType
     */
    @WebEndpoint(name = "CarianPersendirian_OnlineHttpPort")
    public CarianPersendirianOnlinePortType getCarianPersendirianOnlineHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost:8080/carianPersendirianOnlineWS", "CarianPersendirian_OnlineHttpPort"), CarianPersendirianOnlinePortType.class, features);
    }

}
